---
- hosts: servers
  user: root

  tasks:
    - name: set locale
      shell: export LC="en_US.UTF-8" && export LANGUAGU="en_US.UTF-8" && locale >> /etc/environment
 
    - name: Update apt cache
      apt: update-cache=yes

    - name: Install system packages
      apt: name={{item}} state=installed
      with_items:
      - nginx
      - python-setuptools
      - python-mysqldb
      - python-imaging
      - libjpeg8
      - libjpeg62-dev
      - libfreetype6
      - libfreetype6-dev

    - name: Install pip
      easy_install: name=pip

    - name: install virtualenv
      pip: name=virtualenv

    - name: create virtualenv
      shell: virtualenv env

    # - name: virtualenv activate
    #   shell: source ~/python-venv/bin/activate

    - name: Install Djanggo 
      pip: name=Django version=1.5

    - name: Install Djanggo-cms
      pip: name=django-cms

    - name: Install south 
      pip: name=south

    - name: Install Pillow 
      pip: name=Pillow

# vim:ft=ansible: